# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- Dev
variables:
  TEST_ENV: "Dev"
  DEPLOY_URL: ""
  DEPLOY_CREDENTIALS: ""
  WEB_BUID_IMAGE: ""
.build_web: &build_web |-
  cd TestWeb
  npm run build -- --mod $TEST_ENV

.create_zip: &create_zip |-
  apt-get update
  apt-get -y install zip
  zip -r deploy.zip

.deploy: &deploy |-
  curl -X POST --data-binary @deploy.zip $DEPLOY_URL --header "Authorization:Basic $DEPLOY_CREDENTIALS"

dev_web:
  stage: Dev
  image: $WEB_BUID_IMAGE
  tags:
    - dev
  script:
    - TEST_ENV= "Dev"
    - DEPLOY_URL= ""
    - DEPLOY_CREDENTIALS= ""
    - *build_web
    - *create_zip
    - *deploy
  when: manual
  allow_failure: false
  only:
    changes:
      - TestWeb/**/*

